### ISSUE TITLE
Tap to join onging call in ios is missing

### ISSUE THREAD

**Issue by imrobbyrc** [cometchat-pro/cometchat-chat-uikit-ios-swift#31]
### Describe the problem

> Provide a clear and concise description of the issue

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version used:**
- **Other modules/plugins/libraries that might be involved:**

**Comment by imrobbyrc** [comment]
> Rosanne Fernando (CometChat Team) replied:
> 
> Hello there,
> 
> Thanks for reaching out! I am Rosanne from the Support team. 🙂
> 
> I will be happy to assist you. Can you elaborate on the issue you are facing?
> 
> Regards.
> 
> Rosanne Fernando CometChat

hi, currently my team try to implement cometchat with call, we already able to accept or reject call, but if dismissed the app or  the `CometChatMeetingView`, we cant rejoin or open the `CometChatMeetingView` again

my code to rejoin the call is
```swift
guard let call = CometChat.getActiveCall() else { return }
CometChat.startCall(sessionID: call.sessionID ?? "", inView: self.view) { userJoined in
            DispatchQueue.main.async {
                if let name = userJoined?.name {
                    CometChatSnackBoard.display(message: "\(name) " + "JOINED".localized(), mode: .info, duration: .short)
                }
            }
        } onUserLeft: { onUserLeft in
            DispatchQueue.main.async {
                if let name = onUserLeft?.name {
                    CometChatSnackBoard.display(message: "\(name) " + "LEFT_THE_CALL".localized(), mode: .info, duration: .short)
                }
            }
        } onUserListUpdated: { onUserListUpdated in
        } onAudioModesUpdated: { onAudioModesUpdated in
        } onError: { onError in
            DispatchQueue.main.async {
                if let error = onError {
                    CometChatSnackBoard.showErrorMessage(for: error)
                }
            }
        } onCallEnded: { onCallEnded in
            DispatchQueue.main.async {
                self.dismiss(animated: true)
                CometChatSnackBoard.display(message:  "CALL_ENDED".localized(), mode: .info, duration: .short)
                
            }
        }

**Comment by andraantariksa** [comment]
Hi, I'm @imrobbyrc colleague who are working with cometchat Android.

We have [this utilities in android](https://github.com/cometchat-pro/android-kotlin-chat-ui-kit/blob/3f6247c8803cc627678d4bd8d8b1c9b7f3bf8f05/uikit-kotlin/src/main/java/com/cometchat/pro/uikit/ui_resources/utils/Utils.kt#L790-L795) and [used here](https://github.com/cometchat-pro/android-kotlin-chat-ui-kit/blob/3f6247c8803cc627678d4bd8d8b1c9b7f3bf8f05/uikit-kotlin/src/main/java/com/cometchat/pro/uikit/ui_components/messages/message_list/CometChatMessageList.kt#L643-L666). However, we couldn't find similar functionality in iOS. Could you help us out?

**Comment by imrobbyrc** [comment]
> Rosanne Fernando (CometChat Team) replied:
> 
> Thank you for providing more details. Could you please specify the version of the UI kit you are currently utilizing? Also, are you trying to implement the Ongoing call function in the iOS UI kit?
> 
> Regards.
> 
> Rosanne Fernando CometChat

i'm using uikit v3, yes im trying to implement call function with you IOS UI Kit

**Comment by imrobbyrc** [comment]
Halo @cometchat-helpcenter-bot

**Comment by fzld** [comment]
hi @cometchat-helpcenter-bot we have already made customizations in the UI Kit that we use as per now.

since this issue is closed I assume that this problem is resolved? i dont think its possible to update the UI Kit to v4 since we already implement and customize the UI Kit v3. how should we implement this one then?

Thanks
